apiVersion: v1
kind: Namespace
metadata:
  name: ideaforge-ai  # Will be replaced by eks-prepare-namespace target
  labels:
    name: ideaforge-ai  # Will be replaced by eks-prepare-namespace target
    app: ideaforge-ai

