apiVersion: v1
kind: Namespace
metadata:P890-ideaforge-ai-dev-58a50  # Will be replaced by eks-prepare-namespace target
  labels:P890-ideaforge-ai-dev-58a50  # Will be replaced by eks-prepare-namespace target
    app: ideaforge-ai

